let mockData=[
    {
        name:'makeup',
        url:'http://worker-images.ws.pho.to/i1/FFF28021-BF19-4B7B-82DF-3902075403A7.jpg',
        code:`<image_process_call>
        <image_url></image_url>
        <methods_list>
          <method>
          <name>makeup</name>
          <params>use_skin_healing=true;use_eyes_enhancement=true;use_teeth_whitening=true;use_portrait_filters=true;use_flash_healing=true;use_wrinkles_healing=true;use_auto_red_eye=false</params>
          </method>
        </methods_list>
        <result_size>1400</result_size>
        <result_quality>90</result_quality>
        <template_watermark>true</template_watermark>
        <lang>en</lang>
        <abort_methods_chain_on_error>true</abort_methods_chain_on_error>
      </image_process_call>`
    },
    {
        name:'sunny_colors',
        url:'http://worker-images.ws.pho.to.s3.amazonaws.com/i1/100234CC-73AF-47A3-ADA2-BDFFF5AEC2E9.jpg',
        code:`<image_process_call>
        <image_url></image_url>
        <methods_list>
          <method>
            <name>sunny_colors</name>
          </method>
        </methods_list>
        <result_size>1400</result_size>
        <result_quality>90</result_quality>
        <template_watermark>true</template_watermark>
        <lang>en</lang>
        <abort_methods_chain_on_error>true</abort_methods_chain_on_error>
      </image_process_call>`
    },
    {
        name:'split_toning',
        code:`<image_process_call>
        <image_url></image_url>
        <methods_list>
          <method>
            <name>split_toning</name>
            <params>desaturate=0;balance=48;shadow_hue=222;highlight_hue=44;shadow_saturation=100;highlight_saturation=94</params>
          </method>
        </methods_list>
        <result_size>1400</result_size>
        <result_quality>90</result_quality>
        <template_watermark>true</template_watermark>
        <lang>en</lang>
        <abort_methods_chain_on_error>true</abort_methods_chain_on_error>
      </image_process_call>`,
      url:'http://worker-images.ws.pho.to/i1/4832A103-8717-40F8-A78A-D224E7B7EE11.jpg'
    },
    {
        name:'vintage',
        code:`<image_process_call>
        <image_url></image_url>
        <methods_list>
          <method>
            <name>vintage</name>
            <params>palette_type=0</params>
          </method>
        </methods_list>
        <result_size>1400</result_size>
        <result_quality>90</result_quality>
        <template_watermark>true</template_watermark>
        <lang>en</lang>
        <abort_methods_chain_on_error>true</abort_methods_chain_on_error>
      </image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/693329B3-7310-4691-ADEB-892224BAC15C.jpg'
    },
    {
        name:'vintage',
        code:`<image_process_call>
        <image_url></image_url>
        <methods_list>
          <method>
            <name>vintage</name>
            <params>palette_type=1</params>
          </method>
        </methods_list>
        <result_size>1400</result_size>
        <result_quality>90</result_quality>
        <template_watermark>true</template_watermark>
        <lang>en</lang>
        <abort_methods_chain_on_error>true</abort_methods_chain_on_error>
      </image_process_call>`,
        url:'http://worker-images.ws.pho.to.s3.amazonaws.com/i1/7369AF4B-276A-402D-B4DC-0A8B98A91275.jpg'
    },
    {
        name:'vintage',
        code:`<image_process_call>
        <image_url></image_url>
        <methods_list>
          <method>
            <name>vintage</name>
            <params>palette_type=2</params>
          </method>
        </methods_list>
        <result_size>1400</result_size>
        <result_quality>90</result_quality>
        <template_watermark>true</template_watermark>
        <lang>en</lang>
        <abort_methods_chain_on_error>true</abort_methods_chain_on_error>
      </image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/65EB09DE-4CA9-468B-83D9-EACFBE2B99CE.jpg'
    },
    {
        name:'vintage',
        code:`<image_process_call>
        <image_url></image_url>
        <methods_list>
          <method>
            <name>vintage</name>
            <params>palette_type=3</params>
          </method>
        </methods_list>
        <result_size>1400</result_size>
        <result_quality>90</result_quality>
        <template_watermark>true</template_watermark>
        <lang>en</lang>
        <abort_methods_chain_on_error>true</abort_methods_chain_on_error>
      </image_process_call>`,
        url:'http://worker-images.ws.pho.to.s3.amazonaws.com/i1/FAB53022-D456-4B6C-8168-875F7220C82B.jpg'
    },
    {
        name:'vintage',
        code:`<image_process_call>
        <image_url></image_url>
        <methods_list>
          <method>
            <name>vintage</name>
            <params>palette_type=4</params>
          </method>
        </methods_list>
        <result_size>1400</result_size>
        <result_quality>90</result_quality>
        <template_watermark>true</template_watermark>
        <lang>en</lang>
        <abort_methods_chain_on_error>true</abort_methods_chain_on_error>
      </image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/5CC56B86-F015-4325-A80A-51111EDF17C2.jpg'
    },
    {
        name:'dry_brush',
        code:`<image_process_call>
        <image_url></image_url>
        <methods_list>
          <method>
          <name>dry_brush</name>
          </method>
        </methods_list>
        <result_size>1400</result_size>
        <result_quality>90</result_quality>
        <template_watermark>true</template_watermark>
        <lang>en</lang>
        <abort_methods_chain_on_error>true</abort_methods_chain_on_error>
      </image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/4BC56DD0-C02A-433D-95F6-40A6BA6D1F96.jpg'
    },
    {
        name:'vintage-charcoal-sketch',
        code:`<image_process_call><image_url order="1"></image_url><methods_list><method order="1"><name>collage</name><params>template_name=vintage_charcoal_sketch</params></method></methods_list><result_size>1400</result_size><result_quality>90</result_quality><template_watermark>true</template_watermark><lang>en</lang><abort_methods_chain_on_error>true</abort_methods_chain_on_error></image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/3CD6776F-045F-49AB-A09A-5859E718FCAC.jpg'
    },
    {
        name:'old-photo-effect',
        code:`<image_process_call><image_url order="1"></image_url><methods_list><method order="1"><name>collage</name><params>template_name=old_photo</params></method></methods_list><result_size>2000</result_size><result_quality>90</result_quality><template_watermark>true</template_watermark><lang>en</lang><abort_methods_chain_on_error>true</abort_methods_chain_on_error></image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/DB2C37BC-09BC-46BE-89E9-0A68A0F319A7.jpg',
    },
    {
        name:'photography_in_drawing',
        code:`<image_process_call><image_url order="1"></image_url><methods_list><method order="1"><name>collage</name><params>template_name=photography_in_drawing</params></method></methods_list><result_size>1400</result_size><result_quality>90</result_quality><template_watermark>true</template_watermark><lang>en</lang><abort_methods_chain_on_error>true</abort_methods_chain_on_error></image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/6B5A21B4-41E5-484F-8CD4-F2F90039ED71.jpg'
    },
    {
        name:'birthday_balloons',
        code:`<image_process_call><image_url order="1"></image_url><methods_list><method order="1"><name>collage</name><params>template_name=birthday_balloons</params></method></methods_list><result_size>1400</result_size><result_quality>90</result_quality><template_watermark>true</template_watermark><lang>en</lang><abort_methods_chain_on_error>true</abort_methods_chain_on_error></image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/45A7E0D8-16E0-4BC8-BA19-4D740DB5286B.jpg'
    },
    {
        name:'wedding_march',
        code:`<image_process_call><image_url order="1"></image_url><methods_list><method order="1"><name>collage</name><params>template_name=wedding_march</params></method></methods_list><result_size>1400</result_size><result_quality>90</result_quality><template_watermark>true</template_watermark><lang>en</lang><abort_methods_chain_on_error>true</abort_methods_chain_on_error></image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/4E4D460E-EE3F-4020-9375-52F5F441855B.jpg'
    },
    {
        name:'ocean_paradise',
        code:`<image_process_call><image_url order="1"></image_url><methods_list><method order="1"><name>collage</name><params>template_name=ocean_paradise</params></method></methods_list><result_size>1400</result_size><result_quality>90</result_quality><template_watermark>true</template_watermark><lang>en</lang><abort_methods_chain_on_error>true</abort_methods_chain_on_error></image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/1CAD653B-2714-49D1-A49B-347CA8B0EB3F.jpg'
    },
    {
        name:'icy_window',
        code:`<image_process_call><image_url order="1"></image_url><methods_list><method order="1"><name>collage</name><params>template_name=icy_window</params></method></methods_list><result_size>1400</result_size><result_quality>90</result_quality><template_watermark>true</template_watermark><lang>en</lang><abort_methods_chain_on_error>true</abort_methods_chain_on_error></image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/BC2EB4CF-3CD7-491E-BC08-2ED8189848E3.jpg'
    },
    {
        name:'retro_film',
        code:`<image_process_call><image_url order="1"></image_url><methods_list><method order="1"><name>collage</name><params>template_name=retro_film</params></method></methods_list><result_size>2000</result_size><result_quality>90</result_quality><template_watermark>true</template_watermark><lang>en</lang><abort_methods_chain_on_error>true</abort_methods_chain_on_error></image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/79E30778-380F-48B8-8940-731ED0A4B145.jpg'
    },
    {
        name:'triptych_effect',
        code:`<image_process_call><image_url order="1"></image_url><methods_list><method order="1"><name>collage</name><params>template_name=triptych_effect</params></method></methods_list><result_size>2000</result_size><result_quality>90</result_quality><template_watermark>true</template_watermark><lang>en</lang><abort_methods_chain_on_error>true</abort_methods_chain_on_error></image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/E9AEAADA-D13E-4991-AE81-814FD8B4D283.jpg'
    },
    {
        name:'elephant_artist',
        code:`<image_process_call><image_url order="1"></image_url><methods_list><method order="1"><name>collage</name><params>template_name=elephant_artist</params></method></methods_list><result_size>1400</result_size><result_quality>90</result_quality><template_watermark>true</template_watermark><lang>en</lang><abort_methods_chain_on_error>true</abort_methods_chain_on_error></image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/EF5BDE16-C49C-4756-B52C-677A4571B8EC.jpg'
    },
    {
        name:'steamed_mirror_effect',
        code:`<image_process_call><image_url order="1"></image_url><methods_list><method order="1"><name>collage</name><params>template_name=steamed_mirror_effect</params></method></methods_list><result_size>2000</result_size><result_quality>90</result_quality><template_watermark>true</template_watermark><lang>en</lang><abort_methods_chain_on_error>true</abort_methods_chain_on_error></image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/AC73A42C-4F07-4204-819D-E2EA86A68290.jpg'
    },
    {
        name:'dramatic_bronze',
        code:`<image_process_call><image_url order="1"></image_url><methods_list><method order="1"><name>collage</name><params>template_name=dramatic_bronze</params></method></methods_list><result_size>1400</result_size><result_quality>90</result_quality><template_watermark>true</template_watermark><lang>en</lang><abort_methods_chain_on_error>true</abort_methods_chain_on_error></image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/FB96D73B-8674-4632-AFCA-4CE1883E99DD.jpg'
    },
    {
        name:'rainbow_sketch',
        code:`<image_process_call><image_url order="1"></image_url><methods_list><method order="1"><name>collage</name><params>template_name=rainbow_sketch</params></method></methods_list><result_size>1400</result_size><result_quality>90</result_quality><template_watermark>true</template_watermark><lang>en</lang><abort_methods_chain_on_error>true</abort_methods_chain_on_error></image_process_call>`,
        url:'http://worker-images.ws.pho.to/i1/D6FC867D-AE43-4DB5-8F7D-1C03B6D968D6.jpg'
    }
]